// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0J3m0biKRNc_kpT8gUVqUV799iU6XKOw',
    appId: '1:124031798661:web:fb0637ac2352253f4788ec',
    messagingSenderId: '124031798661',
    projectId: 'motivationapp-35401',
    authDomain: 'motivationapp-35401.firebaseapp.com',
    storageBucket: 'motivationapp-35401.firebasestorage.app',
    measurementId: 'G-QTJLQXBEX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXSiMrNM0jyr9e7J1VEdX2vaIk2OKDWjA',
    appId: '1:124031798661:android:e544ec51af1722204788ec',
    messagingSenderId: '124031798661',
    projectId: 'motivationapp-35401',
    storageBucket: 'motivationapp-35401.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0J3m0biKRNc_kpT8gUVqUV799iU6XKOw',
    appId: '1:124031798661:web:fb0637ac2352253f4788ec',
    messagingSenderId: '124031798661',
    projectId: 'motivationapp-35401',
    authDomain: 'motivationapp-35401.firebaseapp.com',
    storageBucket: 'motivationapp-35401.firebasestorage.app',
    measurementId: 'G-QTJLQXBEX2',
  );
}
